CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path jan-hq/Vistral-7B-Chat-DPO \
    --dataset alpaca_gpt4_en \
    --template 'llama2' \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir ./models/Vistral-7B-Chat-DPO \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16